source {C:/Xilinx91i/data/projnav/scripts/VsimStopServer.tcl}
-- Auto Generated by Project Navigator to simulate
-- HDL Bencher Annotated Test Bench
--
vlib work
onbreak {resume}
onerror {quit -code 99 -force}
onElabError {resume}
vcom -explicit  -93 "alublock.vhd"
vcom -explicit  -93 "w_alublock.ant"
vsim -t 1ps   -lib work w_alublock
run -all
quit -force
